ViewModels/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HelloWorld.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        public string Name { set; get; }

        [Required]
        [EmailAddress]
        public string Email { set; get; }

        [Required]
        public string Subject { set; get; }

        [Required]
        [MaxLength(250)]
        public string Message { set; get; }
    }
}

Controllers/Web/AppController.cs
using System;
using HelloWorld.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace HelloWorld.Controllers.Web
{
    public class AppController : Controller
    {
        public IActionResult Index() => View();

        public IActionResult Contact() => View();

        public IActionResult Contact(ContactViewModel model)
        {
            return View();
        }
        public IActionResult About() => View();
        
    }

}

Controllers/Web/DutchTreatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HelloWorld.Services;
using HelloWorld.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace HelloWorld.Controllers.Web
{
    public class DutchTreatController : Controller
    {
        private readonly IMailServices _mailServices;

        public DutchTreatController(IMailServices mailServices)
        {
            _mailServices = mailServices;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("contact")]
        public IActionResult Contact()
        {
            ViewBag.Title = "Contact us";

            return View();
        }

        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            if(ModelState.IsValid)
            {
                _mailServices.SendMessage(model.Email, model.Subject, model.Message);
                ViewBag.UserMessage = "Mail sent";
                ModelState.Clear();
            }
            else
            {

            }

            return View();
        }

        public IActionResult About()
        {
            ViewBag.Title = "About us";
            return View();
        }

    }
}

Views/App/About.cshtml
@{
    ViewBag.Title= "About Page";
}
<h2>About page</h2>

Views/App/Contact.cshtml
@model HelloWorld.ViewModels.ContactViewModel
@{
    ViewBag.Title= "Contact Page";
}
@section scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}
<h2>Contact me</h2>
<form method="post">
    <span asp-validation-summary="ModelOnly"></span>
    <label asp-for="Name"></label>
    <input asp-for="Name"/>
    <span asp-validation-for="Name"></span>

    <label asp-for="Email"></label>
    <input type="email" asp-for="Email"/>
    <span asp-validation-for="Email"></span>

    <label asp-for="Message"></label>
    <textarea asp-for="Message" rows="4" cols="40"></textarea>
    <span asp-validation-for="Message"></span>    
    
    <br>
    <input type="submit" value="Submit" />
</form>

Views/App/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<h3>Hello World</h3>

<form>
    <label>Date</label>
    <input type="text" />
    <br>
    <label>Date</label>
    <input type="text" />
    <br>
    <input type="submit" value="Add">
</form>

Views/DutchTreat/About.cshtml
<h2>About</h2>

Views/DutchTreat/Contact.cshtml
@model HelloWorld.ViewModels.ContactViewModel
@{
    ViewBag.Title = "Contact Page";
}
@section scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}
<div class="col-md-6 col-md-offset-3">
<form method="post" class="well">
    <div class="form-group">
        <span asp-validation-summary="ModelOnly"></span>
        <label asp-for="Name"></label> 
        <input asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email"></label> 
        <input type="email" asp-for="Email" class="form-control"/>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Subject"></label>
        <input type="text" asp-for="Subject" class="form-control"/>
        <span asp-validation-for="Subject" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Message"></label>
        <textarea asp-for="Message" rows="4" cols="40" class="form-control"></textarea>
        <span asp-validation-for="Message" class="text-danger"></span>

    </div>
    
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-envelope"></i> Send Message</button>
        <div class="text-success">@ViewBag.UserMessage</div>
    </div>

</form>
</div>

Views/DutchTreat/Index.cshtml
@{ ViewData["Title"] = "Home Page"; }
<div class="row">
    <div class="col-md-9">
        <div class="product-info">
            <img src="~/img/MU.jpg" />
            <h3>Mug</h3>
            <ul class="product-props">
                <li>Price: $9.99</li>
                <li>Artist: Van Gogh</li>
                <li>Title: </li>
                <li>Description: Self-portrait</li>
            </ul>
            <button id="buyButton" class="btn btn-success">Buy</button>
        </div>
        <form id="theForm">
            <label>Your Name:</label>
            <br />
            <input />
            <br />

            <label>Email:</label>
            <br />
            <input type="text" />
            <br />

            <label>Subject:</label>
            <br />
            <input />
            <br />

            <label>Message</label>
            <br />
            <textarea rows="4"></textarea>
            <br />

            <input type="submit" value="Send Message" />
        </form>

        <div>
            <div id="loginToggle">Login</div>
            <form class="popup-form">
                <div>
                    <label>Username</label>
                    <input type="text" />
                </div>
                <div>
                    <label>Password</label>
                    <input type="password" />
                </div>
                <div>
                    <input type="checkbox" />
                    <label>Remember me?</label>
                </div>
                <div>
                    <input type="submit" value="Login" />
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-3"><p>lorem ksjkdajfkdjakfjkadfjkdajfk  ak fkdaj fkdajk jadk jkdaj kdjs kfadjs k</p></div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>The World - @ViewBag.Title</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="~/css/site.css">
    </head>

    <body>
        <div id="sidebar">
            <img src="~/img/MU.jpg" alt="headshot" class="headshot">
            <span id="username">Hello</span>
            <ul class="menu">
                <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
                <li><a asp-controller="App" asp-action="About">About</a></li>
                <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
            </ul>
        </div>
        <div id="wrapper">
            <div id="main">
                <button id="toggleSidebar">Toggle Sidebar</button>
                @RenderBody()
            </div> 
            <div id="footer">
                &copysr; Tin Nguyen - 2017
            </div>
        </div>
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("scripts",false)
    <script type="text/javascript" src="~/js/site.js"></script>

    </body>
</html>

Views/Shared/_LayoutDutchTreat.cshtml
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<title>Dutch Treat @ViewBag.Title</title>
	<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
	<link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet"/>
	<link href="~/css/dutchtreat.css" rel="stylesheet" />
</head>

<body>
	<div class="navbar navbar-inverse">
		<header class="container">
			<div class="navbar-header">
				<div class="navbar-brand"><i class="fa fa-paint-brush fa-spin"></i>Dutch Treat</div>
				<button class="navbar-toggle" data-toggle="collapse" data-target="#menu">&#9776;</button>
			</div>
			<div id="menu" class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li>
						<a asp-controller="DutchTreat" asp-action="Index">Home</a>
					</li>
					<li>
						<a asp-controller="DutchTreat" asp-action="Contact">Contact</a>
					</li>
					<li>
						<a asp-controller="DutchTreat" asp-action="About">About</a>
					</li>
				</ul>
			</div>
			

		</header>
	</div>

	<section class="container">
		<h2 class="text-center">@ViewBag.Title</h2>
		@RenderBody()
	</section>

	<footer class="container">
		<div class="text-center">Copyright 2017</div>
	</footer>

	<script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
	<script src="~/js/index-DucthTreat.js"></script>
	@RenderSection("scripts", false)
</body>

</html>